CC=gcc

hellomake: httpclient-block.c httpclient-nonblock.c
	     $(CC) -o httpclient-block httpclient-block.c
	     $(CC) -o httpclient-nonblock httpclient-nonblock.c

clean:
	rm httpclient-block httpclient-nonblock
